apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: 10.101.209.206:8761/dockertest
  newTag: 03f1708331b0bfc4e68faf557db15cb84c276ff3
resources:
- ./deployment.yaml
- ./service.yaml
