apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: 10.101.209.206:8761/dockertest
  newTag: 3d4fedb311be33ddb286e3ec6e777a40ee07bc50
resources:
- ./deployment.yaml
- ./service.yaml
