apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: 10.101.209.206:8761/dockertest
  newTag: b1dc7793736c01483613572ac19b7c47f6962245
resources:
- ./deployment.yaml
- ./service.yaml
