apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: 10.101.209.206:8761/dockertest
  newTag: c5187abd86c3bf53ec1a7da54db5d1debd1b0e7a
resources:
- ./deployment.yaml
- ./service.yaml
