apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: 10.101.209.206:8761/dockertest
  newTag: 320b227f893afcefddfa72172afb12daa89dbe82
resources:
- ./deployment.yaml
- ./service.yaml
