apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: 10.101.209.206:8761/dockertest
  newTag: 028ad587f890c56d2ed2ab5cbc0cd385fd446b88
resources:
- ./deployment.yaml
- ./service.yaml
