apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: 10.101.209.206:8761/dockertest
  newTag: 1beedc460d3247bc54a14166c475a0348347510d
resources:
- ./deployment.yaml
- ./service.yaml
