apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: 10.101.209.206:8761/dockertest
  newTag: a90ce0f56d69eacb321a415b83f8fda9fec5f2da
resources:
- ./deployment.yaml
- ./service.yaml
