apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: 10.101.209.206:8761/dockertest
  newTag: fd624572bf1921bf118974a190d47f92d1f1e38c
resources:
- ./deployment.yaml
- ./service.yaml
