apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: 10.101.209.206:8761/dockertest
  newTag: 2b8515e975e8cb1cf1aa1ae0867f12aefcaad5dd
resources:
- ./deployment.yaml
- ./service.yaml
