apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
spec:
  selector:
    matchLabels:
      app: demo
  replicas: 2 
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1

  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: demo
        image: 10.101.209.206:8761/dockertest:44c4b23f684add3d1d5577a2d70bbad9dc91e255
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
